spring:
  # 数据库连接
  datasource:
    password: uAiqwVwjJ8-i
    url: jdbc:mysql://120.77.241.43:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root

  # redis
  redis:
    host: bojuecar.6655.la
    port: 6300
    password: test_redis
    # Redis数据库索引（默认为0）
    database: 0
    #连接超时时间（毫秒）
    timeout: 10000

    jedis: #一些常规配置
      pool:
        # 连接池中的最大空闲连接
        max-idle: 60
        # 连接池中的最小空闲连接
        min-idle: 30
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 60000
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200

# 日志配置
logging:
  path: D:/logs