spring:
  profiles:
    active: @profileActive@

  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true

#mybatis 分页
pagehelper:
  supportMethodsArguments: true
  reasonable: true
  helperDialect: mysql
  params: count=countSql

#mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml

#日志配置
logging:
  config: classpath:logback/logback-spring.xml

swagger:
  basePackage: com.springboot.controller
  version: 1.0

my:
  sign: 测试
  test: asfasfasf

# spring 线程池
task:
  pool:
    #核心线程池
    corePoolSize: 500
    #最大线程池
    maxPoolSize: 1000
    #活跃时间
    keepAliveSeconds: 300
    #队列容量
    queueCapacity: 50
